version: "3.8"

services:
  api:
    build:
      context: ./app
      target: base
    env_file:
      - .env
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      API_PORT: "${API_PORT:-8000}"
    depends_on:
      - db
    networks:
      - appnet
    profiles:
      - dev
      - prod
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 3s
      retries: 5

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: appdb
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - appnet
    profiles:
      - dev
      - prod

networks:
  appnet: {}

volumes:
  dbdata: {}
